config/routes.rb
Eyespy::Application.routes.draw do
  resources :guesses

  resources :needles

  resources :players

end

app/models/guess.rb
class Guess < ActiveRecord::Base
end

app/models/needle.rb
class Needle < ActiveRecord::Base
end

app/models/player.rb
class Player < ActiveRecord::Base
  has_many :needles
  has_many :guesses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/guesses_controller.rb
class GuessesController < ApplicationController
  # GET /guesses
  # GET /guesses.xml
  def index
    @guesses = Guess.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @guesses }
    end
  end

  # GET /guesses/1
  # GET /guesses/1.xml
  def show
    @guess = Guess.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @guess }
    end
  end

  # GET /guesses/new
  # GET /guesses/new.xml
  def new
    @guess = Guess.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @guess }
    end
  end

  # GET /guesses/1/edit
  def edit
    @guess = Guess.find(params[:id])
  end

  # POST /guesses
  # POST /guesses.xml
  def create
    @guess = Guess.new(params[:guess])

    respond_to do |format|
      if @guess.save
        format.html { redirect_to(@guess, :notice => 'Guess was successfully created.') }
        format.xml  { render :xml => @guess, :status => :created, :location => @guess }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @guess.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /guesses/1
  # PUT /guesses/1.xml
  def update
    @guess = Guess.find(params[:id])

    respond_to do |format|
      if @guess.update_attributes(params[:guess])
        format.html { redirect_to(@guess, :notice => 'Guess was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @guess.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /guesses/1
  # DELETE /guesses/1.xml
  def destroy
    @guess = Guess.find(params[:id])
    @guess.destroy

    respond_to do |format|
      format.html { redirect_to(guesses_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/needles_controller.rb
class NeedlesController < ApplicationController
  # GET /needles
  # GET /needles.xml
  def index
    @needles = Needle.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @needles }
    end
  end

  # GET /needles/1
  # GET /needles/1.xml
  def show
    @needle = Needle.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @needle }
    end
  end

  # GET /needles/new
  # GET /needles/new.xml
  def new
    @needle = Needle.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @needle }
    end
  end

  # GET /needles/1/edit
  def edit
    @needle = Needle.find(params[:id])
  end

  # POST /needles
  # POST /needles.xml
  def create
    @needle = Needle.new(params[:needle])

    respond_to do |format|
      if @needle.save
        format.html { redirect_to(@needle, :notice => 'Needle was successfully created.') }
        format.xml  { render :xml => @needle, :status => :created, :location => @needle }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @needle.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /needles/1
  # PUT /needles/1.xml
  def update
    @needle = Needle.find(params[:id])

    respond_to do |format|
      if @needle.update_attributes(params[:needle])
        format.html { redirect_to(@needle, :notice => 'Needle was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @needle.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /needles/1
  # DELETE /needles/1.xml
  def destroy
    @needle = Needle.find(params[:id])
    @needle.destroy

    respond_to do |format|
      format.html { redirect_to(needles_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/player_controller.rb
class PlayerController < ApplicationController
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  # GET /players
  # GET /players.xml
  def index
#    @players = Player.all
    @players = Player.find(:all, :order => "score DESC")
#    @players = Article.page(params[:page]).per(10)
    
    render :json => @players
  end

  # GET /players/1
  # GET /players/1.xml
  def show
    @player = Player.find(params[:id])

    render :json => @player
  end


  # POST /players
  # POST /players.xml
  def create
    @player = Player.new(params[:player])
    
    if @player.save
      render :json => @player, :status => :created, :location => @player
    else
      render :json => @player.errors, :status => :unprocessable_entity
    end
  end

  # PUT /players/1
  # PUT /players/1.xml
  def update
    @player = Player.find(params[:id])
    
    if @player.save
      render :json => @player, :status => :ok
    else
      render :json => @player.errors, :status => :unprocessable_entity
    end
  end

  # DELETE /players/1
  # DELETE /players/1.xml
  def destroy
    @player = Player.find(params[:id])
    @player.destroy

    render :json => "Ok", :status => :ok
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guesses_helper.rb
module GuessesHelper
end

app/helpers/needles_helper.rb
module NeedlesHelper
end

app/helpers/player_helper.rb
module PlayerHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/guesses/_form.html.erb
<%= form_for(@guess) do |f| %>
  <% if @guess.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@guess.errors.count, "error") %> prohibited this guess from being saved:</h2>

      <ul>
      <% @guess.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :guessimage %><br />
    <%= f.text_field :guessimage %>
  </div>
  <div class="field">
    <%= f.label :iscorrect %><br />
    <%= f.check_box :iscorrect %>
  </div>
  <div class="field">
    <%= f.label :checked %><br />
    <%= f.check_box :checked %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/guesses/edit.html.erb
<h1>Editing guess</h1>

<%= render 'form' %>

<%= link_to 'Show', @guess %> |
<%= link_to 'Back', guesses_path %>

app/views/guesses/index.html.erb
<h1>Listing guesses</h1>

<table>
  <tr>
    <th>Guessimage</th>
    <th>Iscorrect</th>
    <th>Checked</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @guesses.each do |guess| %>
  <tr>
    <td><%= guess.guessimage %></td>
    <td><%= guess.iscorrect %></td>
    <td><%= guess.checked %></td>
    <td><%= link_to 'Show', guess %></td>
    <td><%= link_to 'Edit', edit_guess_path(guess) %></td>
    <td><%= link_to 'Destroy', guess, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Guess', new_guess_path %>

app/views/guesses/new.html.erb
<h1>New guess</h1>

<%= render 'form' %>

<%= link_to 'Back', guesses_path %>

app/views/guesses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Guessimage:</b>
  <%= @guess.guessimage %>
</p>

<p>
  <b>Iscorrect:</b>
  <%= @guess.iscorrect %>
</p>

<p>
  <b>Checked:</b>
  <%= @guess.checked %>
</p>


<%= link_to 'Edit', edit_guess_path(@guess) %> |
<%= link_to 'Back', guesses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Eyespy</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/needles/_form.html.erb
<%= form_for(@needle) do |f| %>
  <% if @needle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@needle.errors.count, "error") %> prohibited this needle from being saved:</h2>

      <ul>
      <% @needle.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :hint1 %><br />
    <%= f.text_field :hint1 %>
  </div>
  <div class="field">
    <%= f.label :hint2 %><br />
    <%= f.text_field :hint2 %>
  </div>
  <div class="field">
    <%= f.label :hint3 %><br />
    <%= f.text_field :hint3 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/needles/edit.html.erb
<h1>Editing needle</h1>

<%= render 'form' %>

<%= link_to 'Show', @needle %> |
<%= link_to 'Back', needles_path %>

app/views/needles/index.html.erb
<h1>Listing needles</h1>

<table>
  <tr>
    <th>Image</th>
    <th>Hint1</th>
    <th>Hint2</th>
    <th>Hint3</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @needles.each do |needle| %>
  <tr>
    <td><%= needle.image %></td>
    <td><%= needle.hint1 %></td>
    <td><%= needle.hint2 %></td>
    <td><%= needle.hint3 %></td>
    <td><%= link_to 'Show', needle %></td>
    <td><%= link_to 'Edit', edit_needle_path(needle) %></td>
    <td><%= link_to 'Destroy', needle, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Needle', new_needle_path %>

app/views/needles/new.html.erb
<h1>New needle</h1>

<%= render 'form' %>

<%= link_to 'Back', needles_path %>

app/views/needles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Image:</b>
  <%= @needle.image %>
</p>

<p>
  <b>Hint1:</b>
  <%= @needle.hint1 %>
</p>

<p>
  <b>Hint2:</b>
  <%= @needle.hint2 %>
</p>

<p>
  <b>Hint3:</b>
  <%= @needle.hint3 %>
</p>


<%= link_to 'Edit', edit_needle_path(@needle) %> |
<%= link_to 'Back', needles_path %>

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :score %><br />
    <%= f.text_field :score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<h1>Listing players</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Score</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @players.each do |player| %>
  <tr>
    <td><%= player.name %></td>
    <td><%= player.score %></td>
    <td><%= link_to 'Show', player %></td>
    <td><%= link_to 'Edit', edit_player_path(player) %></td>
    <td><%= link_to 'Destroy', player, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<h1>New player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @player.name %>
</p>

<p>
  <b>Score:</b>
  <%= @player.score %>
</p>


<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>